// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAikmXQZ3JYdVFxJkOPaWO0N0nuB3VDBd0',
    appId: '1:945051820712:web:5d1a22a8770f9c3b47589d',
    messagingSenderId: '945051820712',
    projectId: 'imenniroutes',
    authDomain: 'imenniroutes.firebaseapp.com',
    storageBucket: 'imenniroutes.appspot.com',
    measurementId: 'G-H9YX6C0DMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA75ywpGUhLkBbwKnCZkAkZj1CWDrmRf4',
    appId: '1:945051820712:android:213fcb1109b7ae5e47589d',
    messagingSenderId: '945051820712',
    projectId: 'imenniroutes',
    storageBucket: 'imenniroutes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGJrhPfGn9pyak9K4E9jsjWO0jd0kErc',
    appId: '1:945051820712:ios:e5e4955fda8b944f47589d',
    messagingSenderId: '945051820712',
    projectId: 'imenniroutes',
    storageBucket: 'imenniroutes.appspot.com',
    iosBundleId: 'com.example.imenniroutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjGJrhPfGn9pyak9K4E9jsjWO0jd0kErc',
    appId: '1:945051820712:ios:e5e4955fda8b944f47589d',
    messagingSenderId: '945051820712',
    projectId: 'imenniroutes',
    storageBucket: 'imenniroutes.appspot.com',
    iosBundleId: 'com.example.imenniroutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAikmXQZ3JYdVFxJkOPaWO0N0nuB3VDBd0',
    appId: '1:945051820712:web:0e92c95882d54c2147589d',
    messagingSenderId: '945051820712',
    projectId: 'imenniroutes',
    authDomain: 'imenniroutes.firebaseapp.com',
    storageBucket: 'imenniroutes.appspot.com',
    measurementId: 'G-LZKJEKXZ2L',
  );
}
